import LeafFall from './LeafFall'
import SectionHeading from './SectionHeading'

// Widths generated by scripts/build-images.sh. The feature cell tops out near
// 703px and the stacked cells near 498px inside the max-w-7xl layout, so
// 400/800 carry the common cases and 1200/1600 exist for high-DPR displays.
const WIDTHS = [400, 800, 1200, 1600] as const

/** Mirrors the 7/5 split of the desktop grid; one column below md. */
const SIZES = {
  feature:
    '(min-width: 80rem) 703px, (min-width: 48rem) calc((100vw - 4rem) * 0.58), calc(100vw - 3rem)',
  stacked:
    '(min-width: 80rem) 498px, (min-width: 48rem) calc((100vw - 4rem) * 0.41), calc(100vw - 3rem)',
} as const

const srcSet = (base: string, ext: string) =>
  WIDTHS.map((w) => `/images/${base}-${w}.${ext} ${w}w`).join(', ')

type Photo = {
  base: string
  /** Short caption revealed on hover. */
  caption: string
  alt: string
  /** Intrinsic size of the largest derivative, so the img carries a real ratio. */
  width: number
  height: number
}

const PHOTOS: readonly Photo[] = [
  {
    base: 'CaliforniaSkyline',
    caption: 'Ridgelines',
    alt: 'Layered California ridgelines receding into a haze-filled valley under a pale sky',
    width: 1600,
    height: 1067,
  },
  {
    base: 'CuriousFox',
    caption: 'Curious Fox',
    alt: 'A fox sitting on a dirt bank amid tall grass in low light, looking directly at the camera',
    width: 1600,
    height: 1065,
  },
  {
    base: 'BlackAndWhiteBoat',
    caption: 'Moored',
    alt: 'Black and white photograph of a small fishing boat moored beside a weathered wooden pier on flat, still water, with low islands on the horizon',
    width: 1600,
    height: 1067,
  },
]

function Frame({
  photo,
  variant,
  className,
}: {
  photo: Photo
  variant: keyof typeof SIZES
  className: string
}) {
  const sizes = SIZES[variant]
  return (
    <figure className={`group relative overflow-hidden rounded-lg bg-cream shadow-lg ${className}`}>
      <picture>
        <source type="image/avif" srcSet={srcSet(photo.base, 'avif')} sizes={sizes} />
        <source type="image/webp" srcSet={srcSet(photo.base, 'webp')} sizes={sizes} />
        <img
          src={`/images/${photo.base}-800.webp`}
          srcSet={srcSet(photo.base, 'webp')}
          sizes={sizes}
          alt={photo.alt}
          width={photo.width}
          height={photo.height}
          loading="lazy"
          decoding="async"
          className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-[1.06] motion-reduce:group-hover:scale-100"
        />
      </picture>
      <div className="pointer-events-none absolute inset-0 bg-linear-to-t from-[rgba(11,26,17,0.75)] via-transparent to-transparent opacity-0 transition-opacity duration-500 group-hover:opacity-100" />
      <figcaption className="pointer-events-none absolute bottom-0 left-0 flex w-full items-center gap-3 p-5 text-[0.65rem] tracking-[0.28em] text-parchment uppercase opacity-0 transition-all duration-500 group-hover:opacity-100 md:translate-y-2 md:group-hover:translate-y-0 motion-reduce:translate-y-0">
        <span className="block h-px w-6 bg-sage-light" />
        {photo.caption}
      </figcaption>
    </figure>
  )
}

export default function Gallery() {
  const [feature, ...rest] = PHOTOS
  return (
    // Unlike the other sections, this one is full-bleed: the leaf field runs
    // edge to edge, so the container that holds it cannot be the `max-w-7xl`
    // one. The measure moves inward to a wrapper instead, which also keeps the
    // rule at the top the same width as the one above Projects.
    <section id="photography" className="relative isolate overflow-hidden">
      {/* Behind the grid: the negative index puts it under the section's own
          in-flow content, and `isolate` keeps it from falling behind the page. */}
      <LeafFall className="absolute inset-0 -z-10" anchor="#photography-heading" />

      <div className="mx-auto max-w-7xl border-t border-soil/10 px-6 py-20 md:px-8 md:py-24">
        {/* The tree stands on this heading's rule; below it the photo grid would
            cover it. */}
        <div id="photography-heading">
          <SectionHeading
            eyebrow="Landscape &amp; Wildlife"
            title="My"
            accent="Photography"
            index="03"
          />
        </div>

        <div className="mt-10 grid grid-cols-1 gap-4 md:grid-cols-12">
          <Frame
            photo={feature}
            variant="feature"
            className="aspect-[4/3] md:col-span-7 md:row-span-2 md:aspect-auto"
          />
          {rest.map((photo) => (
            <Frame
              key={photo.base}
              photo={photo}
              variant="stacked"
              className="aspect-[3/2] md:col-span-5"
            />
          ))}
        </div>
      </div>
    </section>
  )
}
